### ISSUE TITLE
Easier navigation of detected loads

### ISSUE THREAD

**Issue by SteveManaclaw** [milankarman/auto-loadless#11]
Hey there. Love the new update and the new features it brings, but I have one suggestion that in my experience would significantly improve the program's usability at least for games that have a large amount of loading screens (100+ for example).

I like using the "Snap to detected loads" toggle to quickly skim through a video and see if there's any false-positive frames at the beginnings or ends of detected loads, but I find this feature a bit difficult to use in its current iteration. At the moment it seems the only way to tab through each load in this way is with the mouse on the video scrubber which is bit difficult/straining when you've got to scrub through a bunch of loads and don't want to skip over any for a long run.

I'd love if there was a way to do this with the keyboard or just a button in the UI (maybe next to the "Snap to detected loads" checkbox?) that one could use to move forward/backwards in a way that mimics the scrubber's functionality with this setting checked. I envision something similar to how the forward/backward frame buttons already work, but specifically it would move forward/backward between each load.

At least for my use case this would help a bunch since using the mouse is difficult and clicking on each load individually with the "Go" buttons would be too tedious when just looking to skim through. Thanks.

**Comment by milankarman** [comment]
I like this idea. I'd probably want to make it so you could simultaneously see the frame before the start of a load screen and the frame after the end of a load screen. Definitely going to add this but I won't make any promises on how quickly I'll get it done.

**Comment by Avasam** [comment]
> I like this idea. I'd probably want to make it so you could simultaneously see the frame before the start of a load screen and the frame after the end of a load screen. Definitely going to add this but I won't make any promises on how quickly I'll get it done.

Hi. I came from your Youtube demo (after seeing your Hobbit WR history documentary). And suggested the same thing there.

Being able to confirm load start and end at a glance by showing the frame before and after would increase productivity and usability by a lot.

It could even be a thumbnail preview (1 frame before, 1 frame mid-load, 1 frame after) in the right-side column. Allowing instantaneous visual confirmation without having to click around.

**Comment by milankarman** [comment]
Thanks for the suggestion. I had something similar in mind where you open a separate window showing the load frame and the frame before/after and are able to make quick edits to each frame if needed. Just showing them in another column might be a lot easier though so I'll consider it.

Unfortunately I just haven't really had motivation to work on this so still no promises on when I'll get to it.

**Comment by Avasam** [comment]
Rough draft just for discussion, I was thinking something like this. Where we could see the previous and next frames *out of load* so the visual validation becomes extremely quick:
- When feasable for a game, check if the total number of loads match what you expect
- Then...

| Quickly scroll through the load frames | Or probably even better, this|
|-|-
| ![image](https://user-images.githubusercontent.com/1350584/152837730-3f5d4a5e-6ae2-4807-8013-a3260df27c95.png) | ![image](https://user-images.githubusercontent.com/1350584/152838469-54f197e1-2e97-455b-be85-aec466a25956.png) |

I think it would go a long way in speeding up this step which is important, but currently requires a lot of tedious clicking around.

**Comment by milankarman** [comment]
A list like that seems like a great idea but I think I'd like to keep it separate from the main load list. I'm thinking of adding a button that will open up a window dedicated to checking and fixing the loads which would be pretty much like this but in a dedicated spot.

**Comment by milankarman** [comment]
This is the load checking window layout I think I'll be going with. Feedback and questions are welcome.
![LoadCheckingDesign](https://user-images.githubusercontent.com/34920368/154488211-32fe7cc4-1408-4373-87f8-f57a21e0dc4d.png)

**Comment by Avasam** [comment]
> This is the load checking window layout I think I'll be going with. Feedback and questions are welcome. !

Seems everything is there: previous, first, last, next, and a way to scrub quickly through them all. And it's all pretty clearly indicated.

Since it's not shown in your preview, would it be full images or cropped to the load?

I liked the idea of being able to view multiple / scroll through at a glance. But this works as well.

**Comment by milankarman** [comment]
I was going full frames, no cropping. But I could make cropped preview a toggle if there's demand (let me know).
The reason I ended up going with a full view over a list was because for some console runs with interlacing I want a big view to easily tell when the frames blend.
I also hope this will actually work faster than a list because your eyes don't have to move along with scrolling pictures. Instead you're just able to focus on the same spot while the slider acts similar to a scroll.

**Comment by SteveManaclaw** [comment]
This looks great to me. I don't immediately see anything obvious missing. Should improve usability by quite a lot. Really like the idea of also showing the frames before and after each load- I wouldn't have even thought of that! 

I do agree that having the full frame showing is probably a better default than a cropped view.

**Comment by Avasam** [comment]
Those 4 frame previews are big enough it makes sense to have the full frame. I am sure some games will make it more obvious whether it's a load by looking at the whole image, and it's not so small you loose on important details.

Some might have a different *preference*, but I don't think an option is necessary unless there's a high demand for it.

**Comment by milankarman** [comment]
Implemented in [1.3.0](https://github.com/milankarman/Unload/releases/tag/1.3.0)
