### ISSUE TITLE
[Feature Request] Specify default working directory

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#12]
I would like to be able to specify a working directory for Unload. Here's why:
1. Stay organized. Wherever I take the video from (either from my downloads folder, or my local recordings), the folder of frames will always be in a predetermined location that won't pollute other folders.
2. Drive efficiency. My downloads and local recordings are on my 2TB harddrive. Aka my storage drive. When I load a video into Unload, it'll most likely be from either of those locations, and will create the frames on my slow storage drive, rather than my much preferable M.2 SSD. This is currently a huge bottleneck for me in terms of efficiency.
![image](https://user-images.githubusercontent.com/1350584/152591633-a18241e5-0810-4972-96a8-78d3c6298b9a.png)

Of course I can just move the video over to my SSD (let's say on my desktop). But that's more annoying steps, slowers, and doesn't help with staying organized. While specifying a working directory is a once time thing.

As a bonus: the saved csv file could also default to the specified folder location, with the same default filename as the video (just like the frames folder does)

**Comment by milankarman** [comment]
Personally I'm a big fan of having the frames folder right next to the video folder as for mass verification I just want to download them, check them and delete them right after - but I get why people might want this so I'd probably make it optional and off by default. Not sure when I'll get to it though. Thanks for the suggestion.

**Comment by Avasam** [comment]
This is easy enough to do. I went ahead and started implementing it so you don't have to. I should be done by the end of the day.
![image](https://user-images.githubusercontent.com/1350584/152658884-60895285-dc4a-4200-88b1-f71f70f94e8f.png)

**Comment by milankarman** [comment]
Nice! A pull request would be very welcome

**Comment by milankarman** [comment]
I changed the UI for this a bit to hide it below a settings button in 8c26723934a1579a3f93c1464a0c30f78b0f2103

![XJyWklEYAL](https://user-images.githubusercontent.com/34920368/153421548-06648380-834e-4d03-b7c7-07cf5a3793e3.gif)

**Comment by Avasam** [comment]
> I changed the UI for this a bit to hide it below a settings button in 

Looks great! Definitely satisfies my needs.
Feel free to move "pick loads" back up
