### ISSUE TITLE
Improve load cropping sliders

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#14]
There's two improvements I'd like to see with the sliders:
1. Represent absolute values from the edge, rather than a point and distance.
  At the moment the sliders on the left "move" the image, and those on the right are the image size. This feels unnatural and leads to having to adjust the sliders multiple time even though the cropping was fine previously. (ie: crop left > zoom in > fix vertical crop > fix vertical zoom)

2. I would like to see some sort of labeling or identifier to indicate which slider is which (left, top, right, bottom) without having to remember them by heart.

**Comment by milankarman** [comment]
Putting this here so I don't forget. I'd also like to add a button which then allows you to draw a rectangle over what part you'd like to crop to and instantly applies it.

**Comment by milankarman** [comment]
Here's my implementation, pretty happy with it.

https://user-images.githubusercontent.com/34920368/154817993-a4f48bd2-d636-46df-9994-16ad2062fea7.mp4

**Comment by milankarman** [comment]
Done in [1.3.0](https://github.com/milankarman/Unload/releases/tag/1.3.0)
