### ISSUE TITLE
[Feature request] Include "load times" in the final stats

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#16]
(in the bottom left square and the exported CSV)
Just so I don't have to do the math myself.

Knowing the total loads is useful for console comparison, and offers a quick check to make sure it's not faster than it should be.

**Comment by milankarman** [comment]
Seems useful and easy enough, will do 👍

**Comment by milankarman** [comment]
Implemented in [1.3.0](https://github.com/milankarman/Unload/releases/tag/1.3.0)
