### ISSUE TITLE
[Feature request] Save preferred settings

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#17]
Just like in #12 , there are some settings I believe could benefit from being saved across sessions of Unload.
- Minimum Similarity
- Minimum Frames
- Concurrent tasks
- Fast forward step size
- Snap to detected loads

**Comment by milankarman** [comment]
Seems like a good idea, especially if more features are added in the future. Though I think I want to omit minimum similarity and minimum frames from saved settings, as those settings should be changed for different videos and runs - so getting too comfortable with saved settings there might cause user error. Though maybe it would be a good idea to leave an option for them in a config file anyway for advanced users.

**Comment by Avasam** [comment]
I'll vouch for Minimum Similarity since, for me, 0.95 is 0.0001(~ish, I don't remember exactly) short using pHash for one of the games I verify and tested with. So I set it to 0.96. If it ***really*** has to be an advanced user default value, then so be it. Otherwise I think it will be annoying to forget to update that value and see I have 1 load too many.

**Comment by milankarman** [comment]
How does a checkbox for remembering load detection settings sound? That way it's at least a conscious decision.

**Comment by Avasam** [comment]
> How does a checkbox for remembering load detection settings sound? That way it's at least a conscious decision.

If you think it fits well your UI, that's fine by me.

**Comment by milankarman** [comment]
Implemented in version [1.3.0](https://github.com/milankarman/Unload/releases/tag/1.3.0)
