### ISSUE TITLE
Update documentation from "Concurrent tasks" to "Maximum concurrent tasks"

### ISSUE THREAD

**Issue by Avasam** [milankarman/auto-loadless#19]
1. There's a typo in the readme: "Cocurrent Tasks"
2. It should be "Maximum Concurrent Tasks". As it may actually use *less* (see documentation for MaxDegreeOfParallelism https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.paralleloptions.maxdegreeofparallelism?view=net-6.0 ). Setting it anything higher than the number of logical processors should have no effect as far as I understand. Tests on ***my*** machine seems to concur.
3. Indicate in the documentation that setting it higher than the number of logical processors does nothing (or at least doesn't help). Having to specify the maximum is a very edge case. And anything less is only useful if you'd like to keep using your computer for something else while Unload is converting frames (or if your CPU weirdly has issues with using all cores at once)

Ref for logical processors:
![image](https://user-images.githubusercontent.com/1350584/152705896-a0bcd010-b976-4150-82dd-fb14b740bfa4.png)

(this next one I find optional, especially with the 3 points above and #17)
4. Default "Maximum concurrent tasks" to "Auto" or "Max". (which would not specify a `MaxDegreeOfParallelism` to `ParallelOptions`). Unless this is one of those edge cases `When the thread pool's heuristics is unable to determine the right number of threads to use and could end up injecting too many threads.`

**Comment by milankarman** [comment]
Definitely worth testing/updating. I'll admit that eyeballed the value on this as I was trying a lot of things to optimize so it's worth revisiting.

**Comment by milankarman** [comment]
Played around with it for a little bit and got pretty much the same results as you did. I think I'd rather just remove the setting completely to keep it simple. Lowering it would really be a niche edge case and I think it would just be more confusing to keep it around.

**Comment by milankarman** [comment]
Closing this because the concurrent task setting is removed in version [1.3.0](https://github.com/milankarman/Unload/releases/tag/1.3.0)
