### ISSUE TITLE
Add a progress bar?

### ISSUE THREAD

**Issue by KevinSkull** [milankarman/auto-loadless#3]
After Covert & Load on a file there is no indication of any progress while it takes its time to load the frames would be a nice feature if you could add it.

**Comment by milankarman** [comment]
Heya, thanks for the feedback. Fow now you can read out of the console window it opens when converting. In there it should show you how far in the conversion is. But I agree that a built in progress bar would be nice so that's definitely on the to-do list.

**Comment by KevinSkull** [comment]
Yep no issue when you actually converting but I meant right after the converting is done the program will just act stuck as it's loading in all the frames with the console window being closed automatically.

**Comment by milankarman** [comment]
Ah I see. It hanging like that might be a bug more than anything. Seems like you can convert, reopen the application and load without converting as a workaround if that happens. I'll be sure to investigate.

**Comment by milankarman** [comment]
Fixed and improved in [release 1.1.0](https://github.com/milankarman/Unload/releases/tag/1.1.0). Thanks for the heads-up!
