### ISSUE TITLE
Using multiple Load Frames at the same time

### ISSUE THREAD

**Issue by marysiamzawka** [milankarman/auto-loadless#5]
The speedgame I'd want to use this tool with has 3 different loadscreens. While it is possible to do 3 separate hash/calculate cycles, it'd be cool if one could streamline the process so that less user input is required overall.

**Comment by milankarman** [comment]
This is definitely something I'd like to add

**Comment by milankarman** [comment]
Added in [release 1.1.0](https://github.com/milankarman/Unload/releases/tag/1.1.0). Thanks for the suggestion!
