### ISSUE TITLE
Missing zero in displayed calculated times

### ISSUE THREAD

**Issue by SteveManaclaw** [milankarman/auto-loadless#8]
Hello. I noticed a small issue in the time calculations for times 1-2 frames after the start of a second.

To illustrate the issue I'm seeing, I changed the end frame for a run I was retiming by advancing it by one frame then recalculating the times. Since I am advancing by one frame at a time, each of these times should be one frame longer than the previous, or 0.033 of a second as it's from a 30 FPS video.

Time without (and with) loads with 1 additional frame added to the end time in each successive calculation:
1:55:48.967
1:55:49.0
1:55:49.33 (incorrect, should be 1:55:49.033 since I advanced by one frame)
1:55:49.67 (incorrect, should be 1:55:49.067, same issue as above)
1:55:49.100
1:55:49.133
1:55:49.167
1:55:49.2

The numbers all appear to be correct, but those two noted times are missing a zero. Obviously something like 49.033 seconds and 49.33 seconds are very different things so this could be pretty confusing if one is looking to calculate milliseconds accurately.

**Comment by milankarman** [comment]
Great catch, that's a pretty big error. Thanks for bringing this to my attention, I'll find some time to fix it and do a bug-fix release soon.

**Comment by milankarman** [comment]
Fixed in version [1.1.1](https://github.com/milankarman/Unload/releases/tag/1.1.1). Thanks for the report!

**Comment by SteveManaclaw** [comment]
It looks like this issue has reappeared in the latest release. I think it's identical to before.

So for any times with milliseconds ranging from 0.0 to 0.1 the leading zero is missing (so 0.033 shows up as 0.33 as an example).
