### ISSUE TITLE
Fractional framerate videos crash when trying to advance by .25 seconds.

### ISSUE THREAD

**Issue by SteveManaclaw** [milankarman/auto-loadless#9]
A minor issue, but I've noticed if a video file has a fractional framerate such as 29.97 Unload will crash if you advance the video using the "fast forward" button. 

It works fine when advancing frame-by-frame. It also works fine if I change the framerate in unload to 29 FPS when converting the video to image files, but I also imagine doing so causes some frames from the video to be missing which is not ideal.

**Comment by milankarman** [comment]
Thanks for reporting again. I actually noticed some other regional issues with decimal frame rates that needs fixing as well, so I'll add this to the list of things to fix.

**Comment by milankarman** [comment]
Better late than never, fixed in [1.2.0](https://github.com/milankarman/Unload/releases/tag/1.2.0). Thanks for reporting as always.
